name: test_hot_restart
description: "A new Dart FFI package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cli_config: ^0.1.1
  logging: ^1.1.1
  native_assets_cli: ^0.3.0
  native_toolchain_c: ^0.3.0

dev_dependencies:
  ffi: ^2.0.2
  ffigen: ^9.0.0
  flutter_lints: ^2.0.0
  test: ^1.21.0
