// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Void> Function()>(symbol: 'AllocateResource')
external ffi.Pointer<ffi.Void> AllocateResource();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(symbol: 'ReleaseResource')
external void ReleaseResource(
  ffi.Pointer<ffi.Void> resource,
);

@ffi.Native<ffi.Int Function()>(symbol: 'AllocatedCounter')
external int AllocatedCounter();
